//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slotlogic.MobileApp.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slotlogic.MobileApp.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log in.
        /// </summary>
        internal static string ButtonMainConnect {
            get {
                return ResourceManager.GetString("ButtonMainConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № card.
        /// </summary>
        internal static string EntryMainCardNumber {
            get {
                return ResourceManager.GetString("EntryMainCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID club.
        /// </summary>
        internal static string EntryMainClubId {
            get {
                return ResourceManager.GetString("EntryMainClubId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string EntryMainPassword {
            get {
                return ResourceManager.GetString("EntryMainPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на from.
        /// </summary>
        internal static string LabelCommonFrom {
            get {
                return ResourceManager.GetString("LabelCommonFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на to.
        /// </summary>
        internal static string LabelCommonTo {
            get {
                return ResourceManager.GetString("LabelCommonTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bonuses for today:.
        /// </summary>
        internal static string LabelDrawBonusesForToday {
            get {
                return ResourceManager.GetString("LabelDrawBonusesForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bonuses till.
        /// </summary>
        internal static string LabelDrawBonusesTill {
            get {
                return ResourceManager.GetString("LabelDrawBonusesTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Coupons:.
        /// </summary>
        internal static string LabelDrawCoupons {
            get {
                return ResourceManager.GetString("LabelDrawCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of draw:.
        /// </summary>
        internal static string LabelDrawFinal {
            get {
                return ResourceManager.GetString("LabelDrawFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bonus period:.
        /// </summary>
        internal static string LabelDrawPeriod {
            get {
                return ResourceManager.GetString("LabelDrawPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Card number:.
        /// </summary>
        internal static string LabelPlayerInfoDetailCardNumber {
            get {
                return ResourceManager.GetString("LabelPlayerInfoDetailCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cashback:.
        /// </summary>
        internal static string LabelPlayerInfoDetailCashback {
            get {
                return ResourceManager.GetString("LabelPlayerInfoDetailCashback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello,.
        /// </summary>
        internal static string LabelPlayerInfoDetailHello {
            get {
                return ResourceManager.GetString("LabelPlayerInfoDetailHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PTS:.
        /// </summary>
        internal static string LabelPlayerInfoDetailPts {
            get {
                return ResourceManager.GetString("LabelPlayerInfoDetailPts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status:.
        /// </summary>
        internal static string LabelPlayerInfoDetailStatus {
            get {
                return ResourceManager.GetString("LabelPlayerInfoDetailStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About application.
        /// </summary>
        internal static string LabelSettingsAboutApp {
            get {
                return ResourceManager.GetString("LabelSettingsAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This application is an integral part of the Slotlogic casino management system. The system was created in 2009 and is a universal system serving both casinos and slot machine halls. In 2016, the GLI certificate was obtained, which speaks in favor of high reliability of the system..
        /// </summary>
        internal static string LabelSettingsAboutAppInfo {
            get {
                return ResourceManager.GetString("LabelSettingsAboutAppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application language:.
        /// </summary>
        internal static string LabelSettingsAppLanguage {
            get {
                return ResourceManager.GetString("LabelSettingsAppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string LabelSettingsConfig {
            get {
                return ResourceManager.GetString("LabelSettingsConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contacts.
        /// </summary>
        internal static string LabelSettingsContacts {
            get {
                return ResourceManager.GetString("LabelSettingsContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manufacturer: OOO Technoconsult
        ///Tel.: +7495 150-57-69
        ///E-mail: v@slotlogic.eu
        ///Site: https://slotlogic.eu/.
        /// </summary>
        internal static string LabelSettingsContactsInfo {
            get {
                return ResourceManager.GetString("LabelSettingsContactsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About Club.
        /// </summary>
        internal static string MenuItemAboutClub {
            get {
                return ResourceManager.GetString("MenuItemAboutClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Draws.
        /// </summary>
        internal static string MenuItemDraws {
            get {
                return ResourceManager.GetString("MenuItemDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        internal static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        internal static string MenuItemProfile {
            get {
                return ResourceManager.GetString("MenuItemProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string PickerLanguageEnglish {
            get {
                return ResourceManager.GetString("PickerLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        internal static string PickerLanguageRussian {
            get {
                return ResourceManager.GetString("PickerLanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose language:.
        /// </summary>
        internal static string PickerSettingsTitle {
            get {
                return ResourceManager.GetString("PickerSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string SettingsTemplateTitle {
            get {
                return ResourceManager.GetString("SettingsTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About Club.
        /// </summary>
        internal static string ToolbarAboutClub {
            get {
                return ResourceManager.GetString("ToolbarAboutClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Draws.
        /// </summary>
        internal static string ToolbarDraws {
            get {
                return ResourceManager.GetString("ToolbarDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        internal static string ToolbarSettingsBackButton {
            get {
                return ResourceManager.GetString("ToolbarSettingsBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        internal static string ToolbarTitle {
            get {
                return ResourceManager.GetString("ToolbarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Card is not registered in the system. (error code: 1001).
        /// </summary>
        internal static string TrCodeErrorUser1001 {
            get {
                return ResourceManager.GetString("TrCodeErrorUser1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Card is blocked. (error code: 1002).
        /// </summary>
        internal static string TrCodeErrorUser1002 {
            get {
                return ResourceManager.GetString("TrCodeErrorUser1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Card is replaced. (error code: 1003).
        /// </summary>
        internal static string TrCodeErrorUser1003 {
            get {
                return ResourceManager.GetString("TrCodeErrorUser1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Card series is blocked. (error code: 1004).
        /// </summary>
        internal static string TrCodeErrorUser1004 {
            get {
                return ResourceManager.GetString("TrCodeErrorUser1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Card password is incorrect. (error code: 1005).
        /// </summary>
        internal static string TrCodeErrorUser1005 {
            get {
                return ResourceManager.GetString("TrCodeErrorUser1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Card is expired. (error code: 1006).
        /// </summary>
        internal static string TrCodeErrorUser1006 {
            get {
                return ResourceManager.GetString("TrCodeErrorUser1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect club ID. (error code: 1007).
        /// </summary>
        internal static string TrCodeErrorUser1007 {
            get {
                return ResourceManager.GetString("TrCodeErrorUser1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter card number!.
        /// </summary>
        internal static string TrMainPageEnterCardNumber {
            get {
                return ResourceManager.GetString("TrMainPageEnterCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid card number format. Enter in the format XX-XX-000000..
        /// </summary>
        internal static string TrMainPageEnterCardValid {
            get {
                return ResourceManager.GetString("TrMainPageEnterCardValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Club ID!.
        /// </summary>
        internal static string TrMainPageEnterClubID {
            get {
                return ResourceManager.GetString("TrMainPageEnterClubID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter password!.
        /// </summary>
        internal static string TrMainPageEnterPassword {
            get {
                return ResourceManager.GetString("TrMainPageEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred while retrieving data. Contact SlotLogic support..
        /// </summary>
        internal static string TrMainPageError {
            get {
                return ResourceManager.GetString("TrMainPageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The server is not responding! Contact SlotLogic support..
        /// </summary>
        internal static string TrMainPageErrorServer {
            get {
                return ResourceManager.GetString("TrMainPageErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error!.
        /// </summary>
        internal static string TrTextError {
            get {
                return ResourceManager.GetString("TrTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No Internet, please reconnect..
        /// </summary>
        internal static string TrTextNoInternet {
            get {
                return ResourceManager.GetString("TrTextNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        internal static string TrTextOK {
            get {
                return ResourceManager.GetString("TrTextOK", resourceCulture);
            }
        }
    }
}
